jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        # Node setup

      - name: Install dependencies
        run: npm install

      - name: Build web app
        run: npm run build

      - name: Capacitor sync
        run: npx cap sync android

      - name: Build APK
        working-directory: android
        run: .\gradlew.bat assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Brain-Puzzle-Kids-APK
          path: android/app/build/outputs/apk/debug/*.apk
